version: 2
jobs:
  one:
    docker:
      - image: alpine:3.10.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo First Hello.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Make!
          command: |
            ls
            ./make
  two:
    docker:
      - image: alpine:3.10.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Second Hello.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Print the Current Time
          command: |
            gcc
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
