version: 2.1
jobs:
  one:
    docker:
      - image: alpine:3.10.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo First Hello.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Make!
          command: |
            ls
            ls /
            ls ..
            ls ~
            ls -d $PWD/*
          
  two:
    docker:
      - image: gcc:9.2.0

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Second Hello.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Make!
          command: |
            ls
            gcc -o myapp MyHelloWorld.c
            ./myapp
            ls /
            ls ..
            ls ~
            ls -d $PWD/*
  tree:
    docker:
      - image: dexatek/tfe-python:1.0
        entrypoint: /bin/sh
    working_directory: ~/opt/project/
    steps:
      - checkout
      - run:
          name: Python
          command: |
            ls
            ls /
            ls ..
            ls ~
            ls -d $PWD/*            
        
workflows:
  version: 2.1
  exec_tree:
    jobs:     
      - tree:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
              
              

